"""Script to create sample radar.xlsx file with sales/opportunity data."""

import pandas as pd
from pathlib import Path

# Sample data for sales/opportunity tracking
data = {
    "name": [
        "AWS Migration Phase 1",
        "Azure PostgreSQL Deployment",
        "Multi-Cloud Strategy",
        "Edge Computing POC",
        "5G Network Upgrade",
        "AI-Powered Analytics Platform",
        "Quantum Computing Research",
        "Blockchain Supply Chain",
        "IoT Sensor Network",
        "Cybersecurity Assessment",
        "Data Lake Implementation",
        "Microservices Architecture",
        "Container Orchestration",
        "API Gateway Modernization",
        "Legacy System Decommission",
        "Cloud Cost Optimization",
        "DevOps Transformation",
        "Observability Platform",
        "Zero Trust Security",
        "Green IT Initiative",
    ],
    "ring": [
        "Ready",
        "Ready",
        "Less Than 1 Year",
        "Less Than 1 Year",
        "Less Than 1 Year",
        "1-3 Years",
        "3+ Years",
        "1-3 Years",
        "Less Than 1 Year",
        "Ready",
        "Less Than 1 Year",
        "Ready",
        "Less Than 1 Year",
        "1-3 Years",
        "Ready",
        "Less Than 1 Year",
        "1-3 Years",
        "1-3 Years",
        "1-3 Years",
        "3+ Years",
    ],
    "quadrant": [
        "Infrastructure",
        "Infrastructure",
        "Infrastructure",
        "Emerging Tech",
        "Infrastructure",
        "Applications",
        "Emerging Tech",
        "Emerging Tech",
        "Infrastructure",
        "Services",
        "Infrastructure",
        "Applications",
        "Infrastructure",
        "Applications",
        "Infrastructure",
        "Services",
        "Services",
        "Applications",
        "Services",
        "Emerging Tech",
    ],
    "isNew": [
        False,
        True,
        False,
        True,
        False,
        True,
        True,
        True,
        False,
        False,
        True,
        False,
        True,
        False,
        False,
        True,
        False,
        True,
        True,
        True,
    ],
    "status": [
        "on-track",
        "on-track",
        "at-risk",
        "new",
        "at-risk",
        "new",
        "new",
        "new",
        "on-track",
        "blocked",
        "new",
        "on-track",
        "new",
        "at-risk",
        "on-track",
        "new",
        "at-risk",
        "new",
        "new",
        "new",
    ],
    "description": [
        "<p><strong>AWS Migration Phase 1</strong> involves moving critical workloads to AWS cloud infrastructure. This includes database migration, application refactoring, and security hardening.</p>",
        "<p>Deploy <strong>Azure PostgreSQL</strong> for the new customer portal. Includes high availability setup, backup strategy, and performance optimization.</p>",
        "<p>Develop a comprehensive <strong>multi-cloud strategy</strong> to avoid vendor lock-in and optimize costs across AWS, Azure, and GCP.</p>",
        "<p><strong>Edge Computing POC</strong> to evaluate performance improvements for real-time data processing at customer sites.</p>",
        "<p>Upgrade network infrastructure to support <strong>5G connectivity</strong> for mobile workforce and IoT devices.</p>",
        "<p>Build an <strong>AI-powered analytics platform</strong> using machine learning to provide predictive insights for sales forecasting.</p>",
        "<p>Research <strong>quantum computing</strong> applications for optimization problems in supply chain and logistics.</p>",
        "<p>Implement <strong>blockchain technology</strong> for supply chain transparency and traceability.</p>",
        "<p>Deploy <strong>IoT sensor network</strong> across manufacturing facilities for real-time monitoring and predictive maintenance.</p>",
        "<p>Comprehensive <strong>cybersecurity assessment</strong> and remediation of identified vulnerabilities.</p>",
        "<p>Implement enterprise <strong>data lake</strong> on AWS S3 with Delta Lake for analytics and ML workloads.</p>",
        "<p>Migrate monolithic applications to <strong>microservices architecture</strong> for better scalability and maintainability.</p>",
        "<p>Deploy <strong>Kubernetes</strong> for container orchestration across development and production environments.</p>",
        "<p>Modernize <strong>API gateway</strong> infrastructure with rate limiting, authentication, and monitoring.</p>",
        "<p>Decommission legacy mainframe systems and migrate to modern cloud-native applications.</p>",
        "<p><strong>Cloud cost optimization</strong> initiative to reduce monthly AWS/Azure spending by 30%.</p>",
        "<p><strong>DevOps transformation</strong> program including CI/CD pipelines, infrastructure as code, and automated testing.</p>",
        "<p>Implement comprehensive <strong>observability platform</strong> with metrics, logs, and distributed tracing.</p>",
        "<p>Deploy <strong>zero trust security</strong> model with identity-based access controls and micro-segmentation.</p>",
        "<p><strong>Green IT initiative</strong> to reduce carbon footprint through energy-efficient infrastructure and renewable energy.</p>",
    ],
    "tags": [
        "cloud,aws,migration",
        "cloud,azure,database",
        "cloud,strategy",
        "edge,poc",
        "network,5g",
        "ai,ml,analytics",
        "quantum,research",
        "blockchain,supply-chain",
        "iot,manufacturing",
        "security,assessment",
        "data,analytics",
        "architecture,microservices",
        "kubernetes,containers",
        "api,modernization",
        "legacy,decommission",
        "cloud,cost-optimization",
        "devops,automation",
        "observability,monitoring",
        "security,zero-trust",
        "sustainability,green-it",
    ],
    "link": [
        "https://example.com/aws-migration",
        "https://example.com/azure-postgres",
        None,
        "https://example.com/edge-poc",
        None,
        "https://example.com/ai-analytics",
        None,
        None,
        "https://example.com/iot-sensors",
        "https://example.com/security-assessment",
        None,
        "https://example.com/microservices",
        None,
        None,
        None,
        "https://example.com/cost-optimization",
        None,
        None,
        "https://example.com/zero-trust",
        None,
    ],
    "customer": [
        "Acme Corp",
        "TechStart Inc",
        "Global Enterprises",
        "Manufacturing Co",
        "Telecom Solutions",
        "Retail Giant",
        "Research Labs",
        "Supply Chain Ltd",
        "Factory Systems",
        "Financial Services",
        "Data Analytics Co",
        "Software House",
        "Cloud Native Inc",
        "API Services",
        "Legacy Systems Corp",
        "Multi-Cloud Org",
        "DevOps Team",
        "Platform Engineering",
        "Security First",
        "Green Energy Co",
    ],
    "value": [
        500000,
        250000,
        1000000,
        150000,
        750000,
        800000,
        2000000,
        600000,
        400000,
        300000,
        450000,
        550000,
        350000,
        200000,
        900000,
        400000,
        650000,
        300000,
        500000,
        1500000,
    ],
    "owner": [
        "John Smith",
        "Sarah Johnson",
        "Michael Chen",
        "Emily Davis",
        "Robert Wilson",
        "Lisa Anderson",
        "David Martinez",
        "Jennifer Taylor",
        "James Brown",
        "Maria Garcia",
        "William Lee",
        "Patricia White",
        "Richard Harris",
        "Linda Martin",
        "Thomas Thompson",
        "Barbara Moore",
        "Charles Jackson",
        "Susan Lewis",
        "Daniel Walker",
        "Nancy Hall",
    ],
}

# Create DataFrame
df = pd.DataFrame(data)

# Create data directory if it doesn't exist
data_dir = Path("data")
data_dir.mkdir(exist_ok=True)

# Write to Excel
output_path = data_dir / "radar.xlsx"
df.to_excel(output_path, sheet_name="Radar", index=False, engine="openpyxl")

print(f"✅ Created sample data file: {output_path}")
print(f"   - {len(df)} entries")
print(f"   - Rings: {df['ring'].unique().tolist()}")
print(f"   - Quadrants: {df['quadrant'].unique().tolist()}")
print(f"   - Statuses: {df['status'].unique().tolist()}")

# Made with Bob
